### ISSUE TITLE
读取界面配置报错

### ISSUE THREAD

**Issue by shuyabin** [CodeNeedWho/JsDroid3#9]
```
{
  "key1": {
    "name": "编号",
    "value": "1"
  }
}

@Field number = readConfig("key1", "1");


result:java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.jsdroid.sdk.apps.Apps.readConfig(java.lang.String, java.lang.String)' on a null object ref
erence
        at com.jsdroid.script.JsDroidScript.readConfig(JsDroidScript.java:622)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:177)
        at MainScript.<init>(MainScript.groovy:10)
        at java.lang.Class.newInstance(Native Method)
        at com.jsdroid.sdk.scripts.Scripts.createGroovyScriptFromJsd(Scripts.java:172)
        at com.jsdroid.server.JsDroidShell$5.run(JsDroidShell.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)


```

**Comment by lu9944** [comment]
不能用@Field，你为什么要用@Field呢？全局变量直接定义就好了。
正确代码如下：
```
number = readConfig("key1", "1");

print(number)
```

**Comment by shuyabin** [comment]
谢谢大佬,我去掉field就行了。哈哈哈
